[package]
name = "vtk-rs"
version = "0.1.0"
edition = "2024"

[lib]
name = "vtk_rs"
crate-type = ["staticlib"]

[dependencies]
eframe = { git = "https://github.com/Gerharddc/egui.git" }
env_logger = "0.11.8"
