[package]
name = "vtk-rs"
version = "0.1.0"
edition = "2024"

[lib]
name = "vtk_rs"
crate-type = ["staticlib"]

[dependencies]
glow = "0.16"
glutin = "0.31"
glutin-winit = "0.4"
raw-window-handle = "0.5"
winit = { version = "0.29", features = ["rwh_05"] }
